import type { NextPage } from 'next';
import Head from 'next/head';
import styles from './landingStyles.module.css';
import SlideLofiGirl from '../components/SlideLofiGirl/SlideLofiGirl';
import Social from '../components/Social/Social';
import LatestRelease from '../components/LatestRelease/LatestRelease';
import Merch from '../components/Merch/Merch'
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SlideLofiGirl />
      <Social listenNow={true} />
      <LatestRelease />
      <Merch/>
      <Social listenNow={false} />
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
      <h1>well hello there</h1>
    </>
  );
};

export default Home;
